//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaizen_Productos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> stock { get; set; }
    }
}
